### ISSUE TITLE
Python action servers cannot be stopped, so...

### ISSUE THREAD

**Issue by corot** [ros/actionlib#48]
...they keep publishing action status until destroyed:
http://docs.ros.org/diamondback/api/actionlib/html/action__server_8py_source.html#L00326

This is not a big drama, but some of my rostests require fake action servers that keep publishing on status topic once the client is shutdown, throwing this exception:

```
Exception in thread Thread-9:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self._target(*self.args, **self._kwargs)
File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/action_server.py", line 57, in ros_timer
callable()
File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/action_server.py", line 303, in publish_status_async
self.publish_status();
File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/action_server.py", line 329, in publish_status
self.status_pub.publish(status_array)
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 852, in publish
self.impl.publish(data)
File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 1011, in publish
raise ROSException("publish() to a closed topic")
ROSException: publish() to a closed topic
```

An ugly hack is to set action_server.started = False, but I don't think this is the intended way to shutdown an action server.

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
